spring.config.activate.on-profile=mysql

spring.datasource.url=jdbc:mysql://localhost:3307/physioclinic?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=physio
spring.datasource.password=Physio#123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hikari (optional)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000

# Make Flyway use the same creds explicitly (belt & suspenders)
spring.flyway.user=physio
spring.flyway.password=Physio#123
spring.flyway.schemas=physioclinic
