
# --- JWT Configuration ---
app.jwt.secret=toXhyLxvdxQQ09vnOvF8gCfSkoympSuY4wM8dSHytQk=
app.jwt.expiration=86400000
# =========================
# JPA / Hibernate (dev)
# =========================
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# =========================
# Flyway (dev)
# =========================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1
spring.flyway.clean-disabled=true
# Actuator on its own port
management.server.port=9093
management.server.address=127.0.0.1
management.endpoints.web.base-path=/actuator

# Expose the endpoints we need for debugging
management.endpoints.web.exposure.include=health,info,metrics,mappings,beans,conditions,loggers,logfile,env,configprops,httpexchanges
management.endpoint.health.show-details=always
management.endpoint.logfile.enabled=true



server.error.include-exception=false
logging.level.org.springframework.web.bind=DEBUG
logging.file.name=logs/physio.log
# show detailed binding/validation errors in responses

server.error.include-message=always
server.error.include-binding-errors=always
logging.level.org.springframework.web=DEBUG




server.error.include-stacktrace=ALWAYS
logging.level.org.springframework.validation=TRACE
logging.level.org.springframework.http.converter.json=TRACE



# Show component names AND their details in the JSON
management.endpoint.health.show-components=always
# Only document our REST layer
springdoc.packagesToScan=com.clinic.physioclinic.controller,com.clinic.physioclinic.web
springdoc.pathsToMatch=/api/**

# Optional but helpful
springdoc.remove-broken-reference-definitions=true
springdoc.show-actuator=false

# Debug Springdoc (temporarily)
logging.level.org.springdoc=DEBUG



management.endpoint.health.probes.enabled=true


logging.level.com.clinic=DEBUG
logging.level.root=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
