spring.application.name=physio-clinic
server.port=9092

# Default profile when none is provided
spring.profiles.default=dev

# JPA
spring.jpa.open-in-view=false

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Swagger/OpenAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
# --- JWT ---
app.jwt.secret=VmVyeS1sb25nLXN0YXRpYy1iYXNlNjQtc2VjcmV0LXN0cmluZy1jaGFuZ2UtbWUtaW4tcHJvZA==
app.jwt.expiration.minutes=120

spring.profiles.group.dev=dev,mysql

# See which handler/mapping breaks
logging.level.org.springframework.boot.actuate.endpoint.web.mappings=DEBUG
logging.level.org.springframework.web.servlet.handler=DEBUG
logging.level.org.springframework.web.method=DEBUG

# (Optional) broader web signals
logging.level.org.springframework.web=INFO
